spring:
  application:
    name: Discovery Server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false 
    service-url:
      defaultZone: http://localhost:8000/eureka  
server:
  port: 8000
  
---
spring:
  profiles: peer1
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-pear2:${peer2.port}/eureka
  instance:
    appname: Cluster
    hostname: eureka-pear1

---
spring:
  profiles: peer2
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-pear1:${peer1.port}/eureka
  instance:
    appname: Cluster
    hostname: eureka-pear2 