server:
  port: 8002
  
spring: 
 application:
    name: ConfigServer 
 cloud:
    config:
      server:
        git:
          uri: https://github.com/ArunKumarDas-120/configuration 
 rabbitmq:    port: 5672
    host: localhost    password: guest    username: guest
    
eureka:
  client: 
    enabled:  false 

---   
spring:
  profiles: DISCOVERY
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance: 
    prefer-ip-address: true
    